site_name: Obsidian Google Lookup Extended
site_url: 'https://k4mp3r.github.io/obsidian-google-lookup'
site_description: Obsidian plugin for Google Contacts and Calendar
site_author: K4mp3r
copyright: MIT

repo_name: 'k4mp3r/obsidian-google-lookup'
repo_url: 'https://github.com/k4mp3r/obsidian-google-lookup'

theme:
  name: material
  features:
    - navigation.tracking

markdown_extensions:
  - meta

nav:
  - 'index.md'
  - 'install.md'
  - 'google-setup.md'
  - 'events.md'
  - 'person.md'
